### ISSUE TITLE
Cannot set custom server url value

### ISSUE THREAD

**Issue by sebastienmusso** [rancher/system-agent#62]
Hello,

I'm trying to use rancher-system-installer with RK2 and a custom RKE2_URL hosted on a loadbalancer.

I set a environment variable in /etc/default/rancher-system-agent (RKE2_SERVER=https://10.0.0.10:9345)
This value is correctly set in /var/lib/rancher/rke2/system-agent-installer/rke2-sa.env file.
But when I what in /etc/rancher/rke2/config.yaml.d/50-rancher.yaml the server url still the primary node ip adress.
even in rke2-server logs the node is registered via primary node ip adress:
"To join node to cluster: rke2 agent -s https://192.168.1.10:9345 -t ${NODE_TOKEN}"

How can I customize this value without modifying /etc/rancher/rke2/config.yaml.d/50-rancher.yaml and restart rke2-server daemon ?

Thanks for you help

**Comment by Oats87** [comment]
@sebastienmusso this issue should probably be filed in `rancher/rancher`. 

We don't support an installation/configuration in this manner -- rancher/provisioningv2 expects Rancher to decide the "server".
