### ISSUE TITLE
Add support for checking component status

### ISSUE THREAD

**Issue by brandond** [rancher/system-agent#8]
From @ibuildthecloud:

The agent should check component healthz or readyz status before indicating that the node install or upgrade is complete (ie updating the plan secret).
This would require checking:
* kubelet for agents
* apiserver and controller-manager for control-plane nodes
* etcd for etcd nodes

These endpoints usually require client cert authentication to access.

**Comment by Oats87** [comment]
More information is needed around this. Technically, subsequent instructions can be defined that are healthchecks.

**Comment by Oats87** [comment]
Synced with @ibuildthecloud this morning around this.

We are going to be building in Kubelet/Kubernetes-like healthz probing that is updated to the plan position (for local) and secret (for remote). 

The datastructure will be similar to:
```
	InitialDelaySeconds int32
	TimeoutSeconds int32
	PeriodSeconds int32
	SuccessThreshold int32
	FailureThreshold int32
```

in addition to a `URL`, `filepath` to a `cacert`, `client-cert`, and `key.
